export const ADD_BRIEF_REQUEST = "ADD_BRIEF_REQUEST";
export const ADD_BRIEF_SUCCESS = "ADD_BRIEF_SUCCESS";
export const ADD_BRIEF_FAILURE = "ADD_BRIEF_FAILURE";

export const FECTH_BRIEF_REQUEST = "FECTH_BRIEF_REQUEST";
export const FECTH_BRIEF_SUCCESS = "FECTH_BRIEF_SUCCESS";
export const FECTH_BRIEF_FAILURE = "FECTH_BRIEF_FAILURE";
